### ISSUE TITLE
internet check blocked for some users

### ISSUE THREAD

**Issue by sirlucidae** [endeavouros-team/EndeavourOS-calamares#11]
A user in the EOS telegram channel reported that the Calamares installer did not detect an internet connection because it was checking GitLab, which is known to block certain countries' IP addresses.

**welcome_online.conf**
`internetCheckUrl:   https://gitlab.com`

From GitLab's webpage:
_Note that IP addresses may be blocked if they are identified as being from a current US embargoed country as per our Terms of Use. Blocks are done automatically through CloudFlare's GeoLocation block methods and cannot be changed. You can enter an IP address to determine how it is classified and verify against the list of countries. A user can consider requesting a data correction of their IP address but it is not guaranteed and GitLab has no control over this process._

**Comment by keybreak** [comment]
>  ...we need connection to GitLab or GitHub for hotfixes and for reading may updated packages lists inside install process.. if both are banned in your country you should use VPN or offline install.

(c) @killajoe https://github.com/endeavouros-team/EndeavourOS-calamares/pull/9#issuecomment-1001253937

**Comment by killajoe** [comment]
My idea is to not rely at all on both of them as sources inside the install process, and instead, have all needed on the ISO. 
So only packages get fetched from the net.
Currently we have the packages lists fetched from git but it has already a fallback using a files from ISO structure. 
And because of file conflict with skel packages i3 is fetching setting files from git again. But this is work in progress and we will find a solution to not need this anymore. 
One workaround idea is to have a switcher that can switch URLs between github and gitlab.. but this is still not 100% ready.

**Comment by killajoe** [comment]
the question is what URL we should use safely to not be blocked ?

**Comment by keybreak** [comment]
Maybe kernel.org?

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/EndeavourOS-calamares/commit/bdea1b2c25803fba547f5070948d4742a0de7761
