### ISSUE TITLE
Different language users need to install different dependency packages.

### ISSUE THREAD

**Issue by 233lol** [endeavouros-team/EndeavourOS-calamares#53]
When I choose KDE, the default PDF reader Okular cannot display Chinese characters because the optional dependency package poppler-data is not installed when the system is installed.
It may not be needed for English users, but other language users need different dependencies.

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/EndeavourOS-calamares/blob/c29b21c26d9a3b7f5e9a2debe85dc6a4557fccbb/calamares/modules/netinstall.yaml#L358

Thanks for mention this issue.. sadly i will more tent to remove okular from install list because it would not be needed .. we can open PDF files with firefox  already..

**Comment by keybreak** [comment]
@killajoe 
Just want to mention that okular can open **much** more formats then just .pdf,..

**Comment by killajoe** [comment]
much more is less KISS ;)  
its not a decision only my tendency and that is what lays down behind every decision on adding or removing packages

**Comment by killajoe** [comment]
and another thing is that there are optional dependencies in many packages we can not just go install any may needed dependency.
Decision is to leave okular installed but not adding dependencies.
Better would be to add it to the wiki
